spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      #enruta por nombre de servicio en Eureka
      discovery:
        locator:
          enabled: true           # crea rutas /{serviceId}/** automáticamente (lowercase)
          lowerCaseServiceId: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway       # habilita /actuator/gateway/**
  endpoint:
    gateway:
      enabled: true
