spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 3s

      # Rutas declarativas (además del locator)
      routes:
        - id: hr
          uri: lb://HR-SVC
          predicates:
            - Path=/hr/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: cb-hr
                fallbackUri: forward:/fallback/hr
            - name: Retry
              args:
                retries: 2
                methods: GET,POST
                statuses: 502,503,504

      # <- AQUÍ va el discovery locator
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/' + serviceId + '/**'"
          filters:
            - name: StripPrefix
              args:
                parts: 1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
