spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true  # rutas /{serviceId}/** en minúsculas

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway   # habilita /actuator/gateway/**
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
