spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,refresh"   # <- necesarios para ver /actuator/gateway/* y refrescar sin reiniciar

endpoint:
  gateway:
    enabled: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # para URLs tipo /identity-svc/**
