logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env"
resilience4j:
  circuitbreaker:
    instances:
      downstream-identity:
        slidingWindowSize: 20
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 60
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      downstream-identity:
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException
  bulkhead:
    instances:
      downstream-identity:
        maxConcurrentCalls: 20
        maxWaitDuration: 0
