server:
  port: 8082
  shutdown: graceful
  tomcat:
    threads:
      max: 100
      min-spare: 10

spring:
  main:
    lifecycle:
      timeout-per-shutdown-phase: 20s
  flyway:
    enable: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://billing-db:5432/billing_local
    username: billing
    password: billing
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          # Usamos el MISMO secreto simétrico del identity-svc (HS256)
          secret-key: ${SECURITY_JWT_SECRET:dev-secret-local}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
http:
  client:
    connect-timeout: 1000   # ms
    read-timeout: 2000
resilience4j:
  circuitbreaker:
    instances:
      downstream-identity:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
  retry:
    instances:
      downstream-identity:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
  bulkhead:
    instances:
      downstream-identity:
        max-concurrent-calls: 20
        max-wait-duration: 0
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
