server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://identity-db:5432/identity_local
    username: identity
    password: identity
  jpa:
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret: ${SECURITY_JWT_SECRET:dev-secret-local}
      expiration-seconds: ${SECURITY_JWT_EXPIRATION_SECONDS:3600}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
